### ISSUE TITLE
Improve Levels

### ISSUE THREAD

**Issue by Ikonedesign** [starvingcats/Leyla#10]
I just uploaded the assets for Levels 1-3.
Use the storyboards below for reference to improve the levels.
Additionally we still need some kind of parallax effect, please implement one using the given foreground and background assets.
- [ ] implement parallax effect

![lvl_1](https://user-images.githubusercontent.com/50525155/72383051-e3dfe500-371a-11ea-8158-86acad5328e2.png)

- [ ] Level 1

![lvl_3](https://user-images.githubusercontent.com/50525155/72383057-e9d5c600-371a-11ea-8cf4-81efcef4f63b.png)

- [ ] Level 2

![lvl_2](https://user-images.githubusercontent.com/50525155/72383059-eb9f8980-371a-11ea-9745-11d4e7b0ab26.png)

- [ ] Level 3

![storyboard lvl4](https://user-images.githubusercontent.com/50525155/73137599-32b24680-405a-11ea-868a-3476bffdb004.png)
#
- [ ] Level 4

![lvl5_storyboard](https://user-images.githubusercontent.com/50525155/73138071-def62c00-405e-11ea-9610-d578e12e8718.png)

- [ ] Level 5

![lvl_6 storyboard](https://user-images.githubusercontent.com/50525155/73208197-4f2bad00-4146-11ea-8108-f105e8194a53.png)

- [ ] Level 6

![blaulicht](https://user-images.githubusercontent.com/50525155/73210922-88b2e700-414b-11ea-9545-6ae85ccdadab.png)

  - [ ] Level 7

![Werbetafel](https://user-images.githubusercontent.com/50525155/73211077-d3346380-414b-11ea-8ad1-3d18412ec5fe.png)

- [ ] Level 8

**Comment by gandie** [comment]
Got it. Like #6 , will start in the next evenings.

**Comment by Ikonedesign** [comment]
Great, can you manage to do it until thursday so i can present it on friday and get some feedback?

**Comment by gandie** [comment]
Reworked lvl1 which was quite painful due to filename guessing problems ( more than one car, typo in grandpa filename etc. ) and scaling issues.

Scaling issues mean that i cannot arrange the sprites relatively to scene size without rescaling images which may furthermore lead to image quality issues. So i have to use a motherload of magic numbers in the code which must be calculated by hand, taking p5js.game coordinate system (X and Y coords are not measured from left bottom corner but from sprite center),  image sizes and all kinds of offsets into account. I do not have a smart answer resolving this problem to stop my brain from melting when calculating layout positions. A good start will be to measure and safe all image sizes in the code, then calculate positions based on these sizes. Changing assets will no stop being painful until this is done properly. This will feel like implementing a framework on top of p5js.game. I allways dreamed of doing such things.

Lesson learned: p5js.game is nice but not really a good choice for doing complex scene layouts. Next time we'll use something more sophisticated, like phaser.js.

Please consider cleaning up the `img` folder, deleting unwanted / deprecated assets will make my life easier.

The start position of character is now flexible which will ease further reworking in other levels.

I did not find any lvl2 background image and i think the checkboxes above do not match the level storyboard shown above the checkbox which is slightly confusing, please check.

Will continue tomorrow.

**Comment by gandie** [comment]
job's done
